# Generated by Django 5.1.5 on 2025-06-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_products_image_url_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="image_url",
            field=models.ImageField(upload_to=""),
        ),
    ]
